### ISSUE TITLE
Mocha and Chai

### ISSUE THREAD

**Issue by ai** [borodean/postcss-assets#12]
Do you have any reason, why you love `tape` instead of `mocha` with `chai`?

`mocha` can get you:

* Better output with colors and readable structure. 
* Better diffs.

I can send PR if you agree to `mocha` (because anyway it is a a matter of taste).

**Comment by borodean** [comment]
@ai, dunno. For the most of the commercial projects we do at @StarterSquad [Jasmine](http://jasmine.github.io/) is used, which I find very useful.

However, for PostCSS Assets I've picked Tape mainly because it was used by some other PostCSS plugin, which I was bootsrapping from. It works fine and looks simple.

However, I believe that this is a point worth thinking.

**Comment by ai** [comment]
Also, according npmjs.com `mocha` is about 4-5 times more popular that `tape`.
